service: ml-api

frameworkVersion: '2'

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  # support for all binary media types
  apiGateway:
    binaryMediaTypes:
      - '*/*'

  # you can overwrite defaults here
  stage: dev
  region: ap-southeast-1

functions:
  vision:
    handler: mllib/vision.main
    events:
      - httpApi:
          path: /vision
          method: post
          request:
            contentHandling: CONVERT_TO_BINARY

  hello:
    handler: mllib/hello.main
    events:
      - httpApi:
          path: /hello
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-plugin-warmup
