service: grabql-api

# app and org for use with dashboard.serverless.com
# app: grabql
# org: mengwangk

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

layers:
  ChromeAws:
    name: ChromeAws
    compatibleRuntimes:
      - nodejs12.x
    description: Chrome AWS Lambda
    package:
      artifact: layers/chrome_aws_lambda.zip

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  bundle:
    forceExclude:
      - chrome-aws-lambda
  serverless-offline:
    location: .webpack/service

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # support for all binary media types
  # https://www.serverless.com/framework/docs/providers/aws/events/apigateway/
  apiGateway:
    binaryMediaTypes:
      - '*/*'

  # you can overwrite defaults here
  stage: dev
  region: ap-southeast-1

  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    DEBUG: ${env:DEBUG}

functions:
  pdfScraper:
    # provisionedConcurrency: 2
    handler: scraper.pdfScraper
    timeout: 60
    layers:
      - { Ref: ChromeAwsLambdaLayer }
    events:
      - http:
          path: scrape_pdf
          method: get
          request:
            contentHandling: CONVERT_TO_BINARY

  pngScraper:
    handler: scraper.pngScraper
    timeout: 60
    layers:
      - { Ref: ChromeAwsLambdaLayer }
    events:
      - http:
          path: scrape_png
          method: get
          request:
            contentHandling: CONVERT_TO_BINARY

  # hello:
  #   handler: hello.main
  #   events:
  #     - http:
  #         path: hello
  #         method: get

  # hello_graphql:
  #   handler: hello_graphql.main
  #   events:
  #     - http:
  #         path: hello_graphql
  #         method: get

#   mock_graphql:
#     handler: mock_graphql.main
#     events:
#       - http:
#           path: mock_graphql
#           method: post
